### ISSUE TITLE
issue with reading data from Excel XLSX 

### ISSUE THREAD

**Issue by Claytex** [modelica-3rdparty/ExternData#10]
Hi, 
I am trying to read a column from an Excel file and then use it in Dymola. Could you please tell me what is the procedure? I am using the ExternData.Types.ExternXLSXFile.constructor function with as input the filename of the excel file, but I get the error: 

```
Error: The class ExternData.Types.ExternXLSXFile is not a package since it contains the
non-constant component id. Lookup in non-package is restricted to 
encapsulated elements, but search found the function constructor.
You can turn off this check by setting Advanced.CheckPackageRestriction:=false;
Component context: ExternData.Types.ExternXLSXFile.id
Component declared as Integer id
File: C:/Program Files (x86)/Dymola 2016 FD01/Modelica/ExternalObject.mo, line 2
Must translate function ExternData.Types.ExternXLSXFile.constructor.
Error: The class ExternData.Types.ExternXLSXFile is not a package since it contains the
non-constant component id. Lookup in non-package is restricted to 
encapsulated elements, but search found the function constructor.
You can turn off this check by setting Advanced.CheckPackageRestriction:=false;
Component context: ExternData.Types.ExternXLSXFile.id
Component declared as Integer id
File: C:/Program Files (x86)/Dymola 2016 FD01/Modelica/ExternalObject.mo, line 2
Failed 
Failed to expand ExternData.Types.ExternXLSXFile.constructor("...path...").
```

After that, I guess I have to use the function ExternData.Functions.XLSX.getReal. Am I correct?

Thanks

**Comment by tbeu** [comment]
Do you use the current master or the last release v1.1.0 of the package? The reason I ask is the currently commented example models in the master head. See https://github.com/tbeu/ExternData/blob/master/ExternData/package.mo#L457-L468 for a commented example which should work in Dymola. Can you please confirm (since I have no Dymola running at the moment)?
If you want to read a column from an Excel sheet you need to call `getReal` in a loop and assign the values to a Real vector (either in an initial equation or with parameter binding).

P.S. The example models will be commented in again for v2.0.0 once they are restructured.

**Comment by Claytex** [comment]
Hi,
I have tried to run the example ExternData.Examples.XLSTest1, but Dymola crashes.
Any idea about what the reason could be?

Thanks

**Comment by tbeu** [comment]
Which version of the package do you use? Which version of Dymola do you use? Which OS do you use Dymola on? Which compiler do you use (MSVC, MinGW or GCC on Linux)? Did you run XLSTest1 or XLSXTest1?

**Comment by tbeu** [comment]
I can now confirm that XLSXTest1 crashes on Dymola 2016 32-bit on Win. Will fix it.
